# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Sebastian Schirner
email:
description: >- # this means to ignore newlines until "baseurl:"
  I am a PhD-Student at the Ruhr-University Bochum. I work at the chair of Social Policy and Public Economics of Prof. Dr. Zohal Hessami. Before starting the PhD, I was working as an economist at the Institute of the German Economy in Cologne. I hold a master's degree in Economics from the University of Cologne.
twitter_username: username
github_username: username
minimal_mistakes_skin: default
search: false

# Build settings
markdown: kramdown
auto_ids: false
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include: ["_pages"]

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

assets:
  css:
    - "/assets/custom.css"

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Sebastian Schirner"
  avatar : "/assets/images/Bild_aktuell_super_small.png"
  bio    : "he/him"
  links:
    - label: "schirner@ifo.de"
      icon: "fas fa-envelope"
      url: ""
    - label: "Detailed CV"
      icon: "fas fa-fw fa-link"
      url: "/CV_Schirner_02_2025.pdf"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/sebastian-schirner-a66684112"

footer:
  links:
    - label: "schirner@ifo.de"
      icon: "fas fa-envelope"
      url: ""
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/sebastian-schirner-a66684112"


defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

atom_feed:
  hide: true

header_pages: ['']

